name: Subir Excel Automáticamente

on:
  schedule:
    - cron: "55 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --local user.email "wjesus88@gmail.com"
          git config --local user.name "walterjesus88"

      - name: Sobrescribir archivo Excel
        run: |
          cp archivo.xlsx $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git add canales_live.csv
          git commit -m "Subir archivo Excel"
          git push origin HEAD:main

