name: Subir Excel Automáticamente

on:
  schedule:
    - cron: "25 20 * * *"

  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v2

      - name: Sobrescribir archivo Excel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "wjesus88@gmail.com"
          git config --local user.name "walterjesus88"     
          git add canales_live.csv
          git commit -m "Subir archivo Excel"
          git push origin HEAD:main
          

