name: Subir Excel Automáticamente

on:
  schedule:
    - cron: "25 19 * * *"

  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --local user.email "wjesus88@gmail.com"
          git config --local user.name "walterjesus88"

      - name: Sobrescribir archivo Excel
        run: |
          cp canales_live.csv $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git add canales_live.csv
          git commit -m "Subir archivo Excel"
          git push origin HEAD:main

