name: Subir Excel

on:
  push:
    paths:
      - canales_live.csv

  schedule:
    - cron: "40 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Subir archivo Excel
        run: |
          git config --global user.name "walterjesus88"
          git config --global user.email "wjesus88@gmail.com"
          git add canales_live.csv
          git commit -m "Subir archivo Excel"
          git push

